# Copyright 2020 Efabless Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

language: minimal

branches:
  only:
    - develop
    - masterploy
    - /^(?i:develop)-.*$/

git:
  submodule: false

services:
    - docker

os: 
  - linux

dist: 
  - bionic 
  - xenial
  - trusty 
  - precise

jobs:
  include:
    - name: "Base Test Magic"
      env: TEST_SET=spm TOOL=magic REPO=magic BRANCH=master
    - name: "Fastest Test Set Magic"
      env: TEST_SET=fastestTestSet TOOL=magic REPO=magic BRANCH=master
    - name: "Typical Test Set 1 Magic"
      env: TEST_SET=typicalTestSet1 TOOL=magic REPO=magic BRANCH=master
    - name: "Typical Test Set 2 Magic"
      env: TEST_SET=typicalTestSet2 TOOL=magic REPO=magic BRANCH=master
    - name: "BM64 Magic"
      env: TEST_SET=BM64 TOOL=magic REPO=magic BRANCH=master
    - name: "picorv32a Magic"
      env: TEST_SET=picorv32a TOOL=magic REPO=magic BRANCH=master
    - name: "chacha Magic"
      env: TEST_SET=chacha TOOL=magic REPO=magic BRANCH=master
    - name: "des Magic"
      env: TEST_SET=des TOOL=magic REPO=magic BRANCH=master
    - name: "md5 Magic"
      env: TEST_SET=md5 TOOL=magic REPO=magic BRANCH=master
    - name: "PPU Magic"
      env: TEST_SET=PPU TOOL=magic REPO=magic BRANCH=master
    - name: "Slowest Test Set Magic"
      env: TEST_SET=slowestTestSet TOOL=magic REPO=magic BRANCH=master
    - name: "Base Test OpenROAD"
      env: TEST_SET=spm TOOL=openroad_flow REPO=OpenROAD BRANCH=openroad
    - name: "Fastest Test Set OpenROAD"
      env: TEST_SET=fastestTestSet TOOL=openroad_flow REPO=OpenROAD BRANCH=openroad
    - name: "Typical Test Set 1 OpenROAD"
      env: TEST_SET=typicalTestSet1 TOOL=openroad_flow REPO=OpenROAD BRANCH=openroad
    - name: "Typical Test Set 2 OpenROAD"
      env: TEST_SET=typicalTestSet2 TOOL=openroad_flow REPO=OpenROAD BRANCH=openroad
    - name: "BM64 OpenROAD"
      env: TEST_SET=BM64 TOOL=openroad_flow REPO=OpenROAD BRANCH=openroad
    - name: "picorv32a OpenROAD"
      env: TEST_SET=picorv32a TOOL=openroad_flow REPO=OpenROAD BRANCH=openroad
    - name: "chacha OpenROAD"
      env: TEST_SET=chacha TOOL=openroad_flow REPO=OpenROAD BRANCH=openroad
    - name: "des OpenROAD"
      env: TEST_SET=des TOOL=openroad_flow REPO=OpenROAD BRANCH=openroad
    - name: "md5 OpenROAD"
      env: TEST_SET=md5 TOOL=openroad_flow REPO=OpenROAD BRANCH=openroad
    - name: "PPU OpenROAD"
      env: TEST_SET=PPU TOOL=openroad_flow REPO=OpenROAD BRANCH=openroad
    - name: "Slowest Test Set OpenROAD"
      env: TEST_SET=slowestTestSet TOOL=openroad_flow REPO=OpenROAD BRANCH=openroad

before_install:
  - docker pull docker/dockerfile:experimental
  - docker pull docker.io/library/node:erbium-alpine
  - sh ./travisCI/travisPrebuild.sh $TOOL
  
install:
  - sh travisCI/travisBuild.sh;
    
script:
  - bash travisCI/travisTest.sh $TEST_SET  